#######################################################################
# In this file, requests will be made from the wordpress event.afup.org
#######################################################################

program:
  path: /{eventSlug}/program
  defaults: {_controller: AppBundle\Controller\Event\Blog\ProgramAction}

speakers:
  path: /{eventSlug}/speakers
  defaults: {_controller: AppBundle\Controller\Event\Blog\SpeakersAction}

planning:
  path: /{eventSlug}/planning
  defaults: {_controller: AppBundle\Controller\Event\Blog\PlanningAction}

talk_widget:
  path: /talk_widget
  defaults: {_controller: AppBundle\Controller\Event\Blog\TalkWidgetAction}
