admin_techletter_generate:
  path: /generate/{techletterId}
  defaults: {_controller: AppBundle\Controller\Admin\TechLetter\GenerateAction}
  requirements:
    techletterId: '\d+'

admin_techletter_preview:
  path: /preview
  defaults: {_controller: AppBundle\Controller\Admin\TechLetter\PreviewAction}

admin_techletter_send_test:
  path: /send_test
  defaults: {_controller: AppBundle\Controller\Admin\TechLetter\SendTestAction}

admin_techletter_retrieve:
  path: /retrieve
  defaults: {_controller: AppBundle\Controller\Admin\TechLetter\RetrieveDataAction}
  methods: ["POST"]

admin_techletter_index:
  path: /
  defaults: {_controller: AppBundle\Controller\Admin\TechLetter\IndexAction}

admin_techletter_history:
  path: /history
  defaults: {_controller: AppBundle\Controller\Admin\TechLetter\HistoryAction}

admin_techletter_members:
  path: /members
  defaults: {_controller: AppBundle\Controller\Admin\TechLetter\MembersAction}
